### ISSUE TITLE
Supplementary Material Download

### ISSUE THREAD

**Issue by ShijieVVu** [Occulte/LEGO_Buildings_Generation#2]
Where are the supplementary materials for the paper? Thank you!

**Comment by Occulte** [comment]
Thank you for your interest! You can find the supplementary materials at the link:
https://mycuhk-my.sharepoint.com/:b:/g/personal/1155209932_link_cuhk_edu_hk/EZ_MISP7W0hPtmn7nr6G7p0BEnHLyn2boEkf5K64HF5Knw?e=AWSX7k
